### ISSUE TITLE
Please update the following components: Clock, ClockWrapper, StyleRoot, StyleSheet, Time, Timepicker

### ISSUE THREAD

**Issue by lazzyms** [catc/react-timekeeper#53] opened 2020-09-04 12:54 UTC
### Warning:Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Clock, ClockWrapper, StyleRoot, StyleSheet, Time, Timepicker

Removing `<React.StrictMode></React.StrictMode>` supress the error but it renders default component, not the one I have modified with adding `props` or css and also not able to change the value.

Versions:
`React: 16.13.1`
`react-timekeeper: 2.1.1`

**Comment by catc** [comment] 2020-09-29 00:33
I updated the react version and added strictmode, but I can't reproduce the warnings. The package shouldn't be using any legacy context. Can you try updating your package and see if it's still an issue?

**Comment by catc** [comment] 2020-10-04 21:09
Closing for now - will reopen if it's still an issue.

**Closed by catc** 2020-10-04 21:09 UTC
