### ISSUE TITLE
broadly theme and style timekeeper

### ISSUE THREAD

**Issue by dotkam** [catc/react-timekeeper#43] opened 2020-02-17 22:03 UTC
First off, version 2.0.4 's AM button needs a float:left. Had to do the following to keep it from being janky:
`.time-picker .react-timekeeper-button-reset:first-child {
  float:left;
}`

Also, looks like tb-hour-wrapper and tb-minute-wrapper are flipped.

I'd like to be able to set colors. Light blue won't work for everyone. I see how I can make the hour and minute text and hands permanently specific colors, but it would be great to have access to what is selected, so that I can actually theme HH:MM depending on what is currently selected (hour or minute wheel).

**Comment by catc** [comment] 2020-02-19 07:29
I'll look into the styling issue - can you post a screenshot without your custom css? I'm also planning on making the lib a little more customizable for styling, mainly colors and such.

**Comment by DaneMane** [comment] 2020-02-27 13:26
Hi, I'm having the same issue styling it to my theme.

I made it work overriding the styles like the following but unfortunetly the class names change when I deploy the project. So the numbers and am/pm buttons are back to default 

```
export const styles = theme => ({
    root:{
        borderRadius: 10,
    },
    timeKeeperWrapper:{
        borderRadius: 10,
        "& .react-timekeeper":{
            borderRadius: 10,
        },
        "& .css-1r6tdpo-Meridiems":{
            "& .css-8xneil-Meridiems":{
                backgroundColor: theme.palette.primary2.light,
                color: 'white',
                // fontWeight:600,
            },
            "& .css-wj4ovw-Meridiems":{
                backgroundColor: theme.palette.primary2.light,
                color: 'white',
                // fontWeight:600,
            },
        },        
        "& .react-timekeeper__tb-minute-wrapper":{
            "& .css-3u52cg-TopBar":{
                color: theme.palette.primary2.light,
            },
            "& .css-2kqqm5-TopBar":{
                color: theme.palette.grey[400],
            }
        },
        "& .react-timekeeper__tb-hour-wrapper":{
            "& .css-1uynwhj-TopBar":{
                color: theme.palette.primary2.light,
            },
            "& .css-1e3on49-TopBar":{
                color: theme.palette.grey[400],
            }
        },
        "& .react-timekeeper__hand-circle-outer":{
            fill: theme.palette.primary2.light,
            opacity:0.25,
        },
        "& .react-timekeeper__hand-circle-center":{
            fill: theme.palette.primary2.light,
            opacity:0.5,
        },
        "& .react-timekeeper__clock-hand":{
            stroke: theme.palette.primary2.light,
            opacity:0.5,
        },
        "& .react-timekeeper__hand-intermediate-circle": {
            fill: theme.palette.primary2.light,
            opacity:0.5,
        }, 
        "& .css-8xz6mk":{
            backgroundColor: theme.palette.primary2.superLight,
            "&:hover":{
                backgroundColor: theme.palette.primary2.superLight,
            }
        }, 
        "& .css-1mrd3l8:hover":{
            backgroundColor: theme.palette.primary2.superLight,
        }
});
```
(using the withStyles method from material ui)

[styled screenshot](https://imgur.com/CQfDWAB)
[deployed screenshot](https://imgur.com/cmHH0Pn)

Thanks in advance!

**Comment by catc** [comment] 2020-03-29 21:35
I added CSS variables to easier style colors/fonts. See https://github.com/catc/react-timekeeper/commit/6d394897f8441d4a8f25a1df20edb6bd76bfb90f

I'll probably do another pass later to add more flexible customization, similar to what you're suggesting @dotkam.

**Comment by rajeev1982** [comment] 2020-04-01 17:59
I have the same issue of styling, so I upgraded to latest version. Now I am getting error when I use the react-timekeeper.

**Comment by catc** [comment] 2020-04-01 18:35
What error? Can you provide a stack trace/screenshot?

**Comment by rajeev1982** [comment] 2020-04-02 13:37
Here is the error I am getting

<img width="859" alt="Screenshot 2020-04-02 at 3 08 08 PM" src="https://user-images.githubusercontent.com/2239359/78255032-60ad7e80-7514-11ea-9a15-0bc3e006ecbc.png">

I am wondering why would you generate css classnames and assign to elements and make it impossible to override styling. Here is a screenshot which shows the only way to identify AM/PM (Also for hour and minute numbers) selection based on autogenerated classname which can not be overridden. I am having to abandon using this component few days before the launch of my app cause the styling just gets screwed up the moment I generate a production build.

<img width="1060" alt="Screenshot 2020-04-02 at 3 10 29 PM" src="https://user-images.githubusercontent.com/2239359/78255373-d9acd600-7514-11ea-829b-9e6cfa1ae0d5.png">

**Comment by catc** [comment] 2020-04-02 17:35
I'll look into it.

**Comment by catc** [comment] 2020-04-02 18:17
The class name issue should be an issue change. I can't reproduce the build error however - created a basic react app, imported the component, did a build and it worked. Can you provide more details? It might be specific to your build tooling.

**Comment by rajeev1982** [comment] 2020-04-03 04:10
Hi Catc, Please ignore the error, I got it fixed in my tooling.

Here are the places where adding classes will help override the styling.

![Screenshot 2020-04-03 at 9 33 19 AM](https://user-images.githubusercontent.com/2239359/78323274-eff77800-758e-11ea-8ea0-4fa2a642abe0.png)

![Screenshot 2020-04-03 at 9 32 48 AM](https://user-images.githubusercontent.com/2239359/78323277-f5ed5900-758e-11ea-906f-898af425f3d9.png)

![Screenshot 2020-04-03 at 9 32 19 AM](https://user-images.githubusercontent.com/2239359/78323284-fa197680-758e-11ea-918a-4a7d0b5504bb.png)

![Screenshot 2020-04-03 at 9 31 23 AM](https://user-images.githubusercontent.com/2239359/78323292-00a7ee00-758f-11ea-9000-b5d9327c5978.png)

![Screenshot 2020-04-03 at 9 38 27 AM](https://user-images.githubusercontent.com/2239359/78323298-04d40b80-758f-11ea-879c-688b0bfb8f7a.png)

Thanks for taking the request.

**Comment by rajeev1982** [comment] 2020-04-03 04:13
Another feature request, not a must have but good to have.

Is it possible to have a config which allows the minutes selections to each five minutes (eg I can select 10:00, 10:05, 10:10 but can't select 10:01, 10:02 etc).

**Comment by catc** [comment] 2020-04-03 05:55
I'm adding an active/selected class for the meridiems (am/pm) and the numbers in the dropdown. For the clock minutes however, those aren't actually ever selected - there's only a clockhand that's placed on top without ever actually changing the styling of the the numbers themselves. If you want to style the clockhand, use css variables as describe in the docs:
```
var(--hand-line-color, #bceaff);
var(--hand-circle-center, #bceaff);
var(--hand-circle-outer, #e6f7ff);
var(--hand-minute-circle, #ade2fb);
```


As for the 5 minute increments, that option already exists - see `forceCoarseMinutes`.

**Comment by catc** [comment] 2020-04-03 06:15
Made changes - https://github.com/catc/react-timekeeper/releases/tag/v2.1.1

Closing this issue.

**Closed by catc** 2020-04-03 06:15 UTC
